"""
priors.py - Prior probability assignments for independent claims.

This file assigns priors to leaf claims (independent premises) based on
their nature: well-established facts, experimental observations, or
methodological details from the source paper.
"""

from .motivation import (
    perovskite_general_formula,
    fapbi3_emergence,
    psc_research_drivers,
    pce_progress,
    operational_stability_progress,
    compositional_engineering_importance,
    fapbi3_phase_transition_problem,
    previous_mixture_approaches,
    alpha_fapbi3_candidate,
    prior_efficiency_record,
    voc_lag,
    previous_anion_engineering,
    formate_previous_studies,
    key_role_of_formate,
    formate_size_fits_vacancy,
    defect_passivation_crystallinity,
)

from .s2_methods import (
    reference_film_preparation,
    fo_fapbi3_film_preparation,
    film_preparation_reproducibility,
    uv_vis_absorption_method,
    photoluminescence_method,
    sem_morphology_method,
    xrd_crystallinity_method,
    solid_state_nmr_method,
    tofsims_composition_method,
    afm_roughness_method,
    j_v_measurement_method,
    eqe_measurement_method,
    eqe_el_measurement_method,
    stability_test_methods,
    md_simulation_method,
    dft_binding_energy_method,
)

from .s3_results import (
    absorption_spectra_results,
    bandgap_identical,
    pl_decay_results,
    reduced_trap_density,
    sem_morphology_results,
    larger_grain_size,
    monolithic_grain_structure,
    surface_roughness_results,
    xrd_phase_results,
    alpha_phase_confirmation,
    improved_crystallinity_2percent,
    gi_xrd_stabilization_results,
    alpha_stabilization_humidity,
    pb207_nmr_results,
    formate_not_in_bulk,
    c13_nmr_formate_environment,
    formate_at_interfaces,
    quantitative_c13_nmr,
    tofsims_confirmation,
)

from .s4_simulation import (
    md_solution_coordination,
    in_situ_crystal_growth,
    md_surface_passivation,
    md_passivation_structure,
    binding_affinity_comparison,
    formate_highest_affinity,
    fa_cation_binding,
)

from .s5_performance import (
    reference_device_performance,
    target_device_performance,
    performance_improvement,
    pcertified_performance,
    eqe_results,
    jsc_verification,
    eqe_el_results,
    non_radiative_recombination_reduction,
    voc_shadowqueisser,
    jsc_light_intensity_linearity,
    voc_light_intensity_ideality,
    reduced_ideality_factor,
    fill_factor_improvement_mechanism,
    formamidinium_acetate_control,
    formate_without_macl,
)

from .s6_stability import (
    shelf_life_stability,
    target_shelf_life_retains_90,
    thermal_stability,
    target_heat_stability_80_percent,
    operational_stability_short_term,
    long_term_operational_stability,
    reference_degradation_mechanism,
    stability_from_crystallinity,
    crystallinity_importance_stability,
    formate_binding_stability,
    low_halide_vacancy_stability,
)

# =============================================================================
# Prior Assignments - mapping label to (prior, justification)
# =============================================================================

PRIOR_DATA = {
    # Well-established background knowledge (0.85-0.95)
    "perovskite_general_formula": (0.95, "Fundamental definition of perovskite crystal structure ABX3"),
    "fapbi3_emergence": (0.90, "Well-established result in PVSK literature"),
    "psc_research_drivers": (0.90, "Established knowledge about PSC research drivers"),
    "pce_progress": (0.90, "Widely reported efficiency progression with multiple sources"),
    "operational_stability_progress": (0.88, "Documented progress in PSC stability"),
    "compositional_engineering_importance": (0.85, "Established principle in PSC optimization"),
    "fapbi3_phase_transition_problem": (0.90, "Well-known issue in FAPbI3 literature"),
    "alpha_fapbi3_candidate": (0.88, "Widely recognized as optimal candidate"),
    "previous_anion_engineering": (0.85, "Established approach in PSC literature"),

    # Strong experimental observations (0.80-0.92)
    "pcertified_performance": (0.92, "Accredited Newport certification of 25.21% PCE"),
    "target_device_performance": (0.90, "Direct J-V measurement with clear protocol"),
    "reference_device_performance": (0.90, "Direct J-V measurement with clear protocol"),
    "performance_improvement": (0.90, "Direct comparison with statistically significant samples"),
    "eqe_results": (0.88, "Direct EQE measurement matching Jsc"),
    "eqe_el_results": (0.88, "Direct EQE_EL measurement with calibrated detector"),
    "non_radiative_recombination_reduction": (0.88, "Derived from EQE_EL ratio measurement"),
    "voc_shadowqueisser": (0.88, "Calculated from EQE_EL measurement, 96% of SQ limit"),

    # Direct experimental results (0.82-0.90)
    "absorption_spectra_results": (0.88, "Direct UV-vis measurement with Tauc plot analysis"),
    "bandgap_identical": (0.88, "Direct derivation from Tauc plot, consistent across samples"),
    "pl_decay_results": (0.85, "Direct time-resolved PL measurement with clear protocol"),
    "reduced_trap_density": (0.85, "Inferred from slower PL decay, consistent with mechanism"),
    "sem_morphology_results": (0.88, "Direct SEM imaging with clear magnification"),
    "larger_grain_size": (0.85, "Direct measurement from SEM images up to 2 μm"),
    "monolithic_grain_structure": (0.85, "Direct observation from cross-sectional SEM"),
    "surface_roughness_results": (0.85, "Direct AFM measurement with specified conditions"),

    # XRD and NMR results (0.82-0.88)
    "xrd_phase_results": (0.85, "Direct XRD measurement with Cu Kα radiation"),
    "alpha_phase_confirmation": (0.88, "XRD peaks at 13.95° and 27.85° match α-FAPbI3"),
    "improved_crystallinity_2percent": (0.85, "Reduced FWHM indicates improved crystallinity"),
    "gi_xrd_stabilization_results": (0.88, "Direct 2D GI-XRD showing δ-phase absence"),
    "alpha_stabilization_humidity": (0.88, "Clear result: δ-phase absent in target, present in reference"),
    "pb207_nmr_results": (0.88, "Direct solid-state NMR with proper referencing"),
    "formate_not_in_bulk": (0.88, "Key NMR finding: resonance unchanged with formate"),
    "c13_nmr_formate_environment": (0.85, "Direct NMR observation of broadened HCOO- peak"),
    "formate_at_interfaces": (0.85, "Inferred from broadened NMR signal distribution"),
    "quantitative_c13_nmr": (0.85, "Integration of resonances for 5.1% MA+ concentration"),
    "tofsims_confirmation": (0.82, "Direct mass spectrometry confirmation"),

    # Simulation results (0.80-0.85)
    "md_solution_coordination": (0.82, "Ab initio MD simulation with proper DFT"),
    "in_situ_crystal_growth": (0.85, "Direct in situ observation of color change"),
    "md_surface_passivation": (0.82, "MD simulation of surface passivation"),
    "md_passivation_structure": (0.82, "Calculated structure with ball-and-stick model"),
    "binding_affinity_comparison": (0.85, "DFT calculated relative binding energies"),
    "formate_highest_affinity": (0.85, "Key DFT finding: HCOO- highest among all anions"),
    "fa_cation_binding": (0.82, "DFT calculated FA+ bonding energies"),

    # Stability measurements (0.82-0.88)
    "shelf_life_stability": (0.85, "Direct aging test over 1000h with periodic measurement"),
    "target_shelf_life_retains_90": (0.85, "Calculated from shelf-life test data"),
    "thermal_stability": (0.85, "Direct heat aging test at 60°C for 1000h"),
    "target_heat_stability_80_percent": (0.85, "Calculated from thermal aging test data"),
    "operational_stability_short_term": (0.85, "Direct 10h MPP tracking measurement"),
    "long_term_operational_stability": (0.88, "450h MPP tracking with periodic J-V curves"),
    "reference_degradation_mechanism": (0.82, "Analysis of Jsc and FF decrease during aging"),
    "stability_from_crystallinity": (0.85, "Mechanistic interpretation consistent with data"),
    "crystallinity_importance_stability": (0.85, "Established principle in perovskite literature"),
    "formate_binding_stability": (0.85, "Explains mechanism linking binding to stability"),
    "low_halide_vacancy_stability": (0.82, "Established relationship in halide perovskite literature"),

    # Methods (0.80-0.85)
    "reference_film_preparation": (0.85, "Well-established preparation protocol"),
    "fo_fapbi3_film_preparation": (0.85, "Defined preparation with 2% FAHCOO"),
    "film_preparation_reproducibility": (0.85, "Controlled conditions stated in paper"),
    "uv_vis_absorption_method": (0.82, "Standard characterization method"),
    "photoluminescence_method": (0.82, "Standard method with clear parameters"),
    "sem_morphology_method": (0.82, "Standard characterization method"),
    "xrd_crystallinity_method": (0.82, "Standard XRD method with Cu Kα"),
    "solid_state_nmr_method": (0.82, "Detailed NMR method with proper referencing"),
    "tofsims_composition_method": (0.82, "Standard mass spectrometry method"),
    "afm_roughness_method": (0.82, "Standard AFM method with specified conditions"),
    "j_v_measurement_method": (0.85, "Standardized J-V measurement with NREL calibration"),
    "eqe_measurement_method": (0.82, "Standard EQE measurement with QEX7 system"),
    "eqe_el_measurement_method": (0.82, "Standard EQE_EL with calibrated Si photodiode"),
    "stability_test_methods": (0.85, "Well-defined stability test protocols"),
    "md_simulation_method": (0.82, "Ab initio MD with proper DFT"),
    "dft_binding_energy_method": (0.82, "Standard DFT for binding energy calculation"),

    # Additional claims
    "previous_mixture_approaches": (0.85, "Well-documented in PSC literature"),
    "prior_efficiency_record": (0.88, "Certified values from literature"),
    "voc_lag": (0.85, "Established observation in FAPbI3 literature"),
    "formate_previous_studies": (0.82, "Documented in MAPbI3 literature"),
    "formate_size_fits_vacancy": (0.85, "Structural fact based on ionic radii"),
    "defect_passivation_crystallinity": (0.88, "Combined effect supported by multiple results"),
    "jsc_verification": (0.88, "EQE integrated Jsc matches measured Jsc"),
    "jsc_light_intensity_linearity": (0.85, "Direct measurement with slope ~0.95"),
    "voc_light_intensity_ideality": (0.85, "Direct measurement of ideality factor"),
    "reduced_ideality_factor": (0.88, "Key metric from light intensity dependence"),
    "fill_factor_improvement_mechanism": (0.85, "Established relationship in solar cell physics"),
    "formamidinium_acetate_control": (0.85, "Control experiment with negative result"),
    "formate_without_macl": (0.82, "Additional control showing formate effect"),
}

# All independent claims
ALL_CLAIMS = [
    perovskite_general_formula,
    fapbi3_emergence,
    psc_research_drivers,
    pce_progress,
    operational_stability_progress,
    compositional_engineering_importance,
    fapbi3_phase_transition_problem,
    previous_mixture_approaches,
    alpha_fapbi3_candidate,
    prior_efficiency_record,
    voc_lag,
    previous_anion_engineering,
    formate_previous_studies,
    key_role_of_formate,
    formate_size_fits_vacancy,
    defect_passivation_crystallinity,
    reference_film_preparation,
    fo_fapbi3_film_preparation,
    film_preparation_reproducibility,
    uv_vis_absorption_method,
    photoluminescence_method,
    sem_morphology_method,
    xrd_crystallinity_method,
    solid_state_nmr_method,
    tofsims_composition_method,
    afm_roughness_method,
    j_v_measurement_method,
    eqe_measurement_method,
    eqe_el_measurement_method,
    stability_test_methods,
    md_simulation_method,
    dft_binding_energy_method,
    absorption_spectra_results,
    bandgap_identical,
    pl_decay_results,
    reduced_trap_density,
    sem_morphology_results,
    larger_grain_size,
    monolithic_grain_structure,
    surface_roughness_results,
    xrd_phase_results,
    alpha_phase_confirmation,
    improved_crystallinity_2percent,
    gi_xrd_stabilization_results,
    alpha_stabilization_humidity,
    pb207_nmr_results,
    formate_not_in_bulk,
    c13_nmr_formate_environment,
    formate_at_interfaces,
    quantitative_c13_nmr,
    tofsims_confirmation,
    md_solution_coordination,
    in_situ_crystal_growth,
    md_surface_passivation,
    md_passivation_structure,
    binding_affinity_comparison,
    formate_highest_affinity,
    fa_cation_binding,
    reference_device_performance,
    target_device_performance,
    performance_improvement,
    pcertified_performance,
    eqe_results,
    jsc_verification,
    eqe_el_results,
    non_radiative_recombination_reduction,
    voc_shadowqueisser,
    jsc_light_intensity_linearity,
    voc_light_intensity_ideality,
    reduced_ideality_factor,
    fill_factor_improvement_mechanism,
    formamidinium_acetate_control,
    formate_without_macl,
    shelf_life_stability,
    target_shelf_life_retains_90,
    thermal_stability,
    target_heat_stability_80_percent,
    operational_stability_short_term,
    long_term_operational_stability,
    reference_degradation_mechanism,
    stability_from_crystallinity,
    crystallinity_importance_stability,
    formate_binding_stability,
    low_halide_vacancy_stability,
]

# Build PRIORS dict
PRIOR = {claim: PRIOR_DATA.get(claim.label, (0.5, f"No prior set for {claim.label}")) for claim in ALL_CLAIMS}

# Gaia expects PRIORS (uppercase S) - assign to PRIORS as well
PRIOR = PRIORS = {claim: PRIOR_DATA.get(claim.label, (0.5, f"No prior set for {claim.label}")) for claim in ALL_CLAIMS}