"""R2R perovskite solar cell package - Weerasinghe et al. 2024, Nature Communications."""

from gaia.lang import (
    claim,
    setting,
    question,
    support,
    infer,
)

# Re-export all public symbols from submodules
from .motivation import (
    perovskite_solar_cell_pce_record,
    lab_scale_limitation,
    vacuum_electrode_cost,
    commercial_tce_cost,
    r2r_promise,
    manufacturing_challenge,
    pfsd_demonstration,
    main_question,
    first_fully_r2r_cells,
    first_fully_r2r_modules,
    high_throughput_platform,
    cost_prediction,
)

from .s2_pfsd import (
    pfsd_technique_description,
    pfsd_advantage,
    shallow_angle_blowing,
    edge_blowing_result,
    xrd_analysis,
    sem_improvement,
    humidity_tolerance,
    pfsd_record_pce,
)

from .s3_automated import (
    carbon_electrode_replacement,
    previous_r2r_cell_pce,
    high_throughput_capability,
    throughput_example,
    maistoi_ratio_effect,
    thicker_film_behavior,
    composition_dependence,
    htab_p3ht_introduction,
    htab_passivation,
    p3ht_heating_requirement,
    htab_p3ht_outperforms,
    reliable_production,
    best_cell_performance,
    film_thickness_range,
)

from .s4_modules import (
    module_scalability,
    five_channel_deposition,
    carbon_ink_deposition,
    silver_grid_design,
    carbon_sheet_resistance,
    module_active_area,
    module_gff,
    module_performance,
)

from .s5_cost import (
    cost_model_development,
    sequence_a_description,
    sequence_b_description,
    sequence_c_description,
    cost_fraction_sequence_a,
    cost_fraction_sequence_b,
    production_cost_area,
    production_cost_power,
    cost_reduction_achieved,
    market_position,
    future_improvement_needed,
    future_cost_potential,
)

from .s6_methods import (
    materials_setting,
    tce_specification,
    ec_binder,
    carbon_pigment,
    pgmesa_solver,
    two_stage_ink_prep,
    pbi2_fai_solution,
    mai_solution,
    htab_solution,
    htm_solutions,
    spiro_meotad_solution,
    rg_coating_etl,
    ir_treatment,
    perovskite_sd_coating,
    htab_p3ht_deposition,
    carbon_electrode_sd,
    silver_grid_printing,
    stripe_pattern,
    five_stripe_flow_rates,
    jv_measurement,
    scan_parameters,
)

from .conclusions import (
    first_demo_conclusion,
    carbon_ink_achievement,
    throughput_system,
    cell_record,
    module_record,
    cost_conclusion,
    future_direction,
)

from .reasoning import (
    strat_r2r_promise,
    strat_manufacturing_challenge,
    strat_pfsd_demonstration,
    strat_pfsd_advantage,
    strat_shallow_angle,
    strat_edge_blowing_result,
    strat_xrd_analysis,
    strat_sem_improvement,
    strat_humidity_tolerance,
    strat_pfsd_record_pce,
    strat_carbon_replacement,
    strat_throughput_example,
    strat_maistoi_ratio,
    strat_thicker_film,
    strat_composition_dependence,
    strat_htab_p3ht_intro,
    strat_htab_outperforms,
    strat_reliable_production,
    strat_film_thickness,
    strat_best_cell,
    strat_module_scale,
    strat_five_channel,
    strat_carbon_ink_deposition,
    strat_carbon_sheet_resistance,
    strat_silver_grid_design,
    strat_module_area,
    strat_module_gff,
    strat_module_performance,
    strat_seq_a,
    strat_seq_b,
    strat_seq_c,
    strat_cost_fraction_a,
    strat_cost_fraction_b,
    strat_production_cost_area,
    strat_production_cost_power,
    strat_cost_reduction,
    strat_market_position,
    strat_future_improvement,
    strat_future_cost,
    strat_first_demo,
    strat_carbon_ink_achievement,
    strat_throughput_system,
    strat_cell_record,
    strat_module_record,
    strat_cost_conclusion,
    strat_future_direction,
    strat_stripe_flow,
)

# Exported conclusions represent the core contributions of this paper
__all__ = [
    # Motivation / context
    "perovskite_solar_cell_pce_record",
    "lab_scale_limitation",
    "vacuum_electrode_cost",
    "commercial_tce_cost",
    "r2r_promise",
    "manufacturing_challenge",
    "pfsd_demonstration",
    "main_question",
    # Main results
    "first_fully_r2r_cells",
    "first_fully_r2r_modules",
    "high_throughput_platform",
    "cost_prediction",
    # PFSD technique
    "pfsd_technique_description",
    "pfsd_advantage",
    "shallow_angle_blowing",
    "edge_blowing_result",
    "xrd_analysis",
    "sem_improvement",
    "humidity_tolerance",
    "pfsd_record_pce",
    # Automated fabrication
    "carbon_electrode_replacement",
    "previous_r2r_cell_pce",
    "high_throughput_capability",
    "throughput_example",
    "maistoi_ratio_effect",
    "thicker_film_behavior",
    "composition_dependence",
    "htab_p3ht_introduction",
    "htab_passivation",
    "p3ht_heating_requirement",
    "htab_p3ht_outperforms",
    "reliable_production",
    "best_cell_performance",
    "film_thickness_range",
    # Module results
    "module_scalability",
    "five_channel_deposition",
    "carbon_ink_deposition",
    "silver_grid_design",
    "carbon_sheet_resistance",
    "module_active_area",
    "module_gff",
    "module_performance",
    # Cost analysis
    "cost_model_development",
    "sequence_a_description",
    "sequence_b_description",
    "sequence_c_description",
    "cost_fraction_sequence_a",
    "cost_fraction_sequence_b",
    "production_cost_area",
    "production_cost_power",
    "cost_reduction_achieved",
    "market_position",
    "future_improvement_needed",
    "future_cost_potential",
    # Methods
    "materials_setting",
    "tce_specification",
    "ec_binder",
    "carbon_pigment",
    "pgmesa_solver",
    "two_stage_ink_prep",
    "pbi2_fai_solution",
    "mai_solution",
    "htab_solution",
    "htm_solutions",
    "spiro_meotad_solution",
    "rg_coating_etl",
    "ir_treatment",
    "perovskite_sd_coating",
    "htab_p3ht_deposition",
    "carbon_electrode_sd",
    "silver_grid_printing",
    "stripe_pattern",
    "five_stripe_flow_rates",
    "jv_measurement",
    "scan_parameters",
    # Conclusions
    "first_demo_conclusion",
    "carbon_ink_achievement",
    "throughput_system",
    "cell_record",
    "module_record",
    "cost_conclusion",
    "future_direction",
]