"""
PVSK Science adk1633 - Bimolecularly passivated interface enables efficient
and stable inverted perovskite solar cells.

This package formalizes the knowledge from Liu et al. (Science 2024) on
bimolecular dual-passivation (DMDP) strategy for inverted perovskite solar cells.
"""

from .motivation import (
    regular_pscs_pce,
    inverted_psc_advantages,
    inverted_psc_pce_gap,
    interface_recombination,
    near_interface_minority_carriers,
    surface_defect_recombination,
    surface_passivation_suppresses,
    single_molecule_insufficient,
    dual_passivation_concept,
    diammonium_field_effect,
    methylthio_chemical_passivation,
)

from .s2_methods import (
    device_architecture,
    control_device_pce,
    dianmmonium_pce_improvement,
    dianmmonium_field_effect_mechanism,
    bai_chemical_passivation,
    aai_improves_baseline,
    methylthio_synthesis,
    dual_combinations_improve,
    pai2_3mtpai_highest_pce,
    strat_dianmmonium_methylthio,
)

from .s3_results import (
    binding_energy_3mtpa,
    vacancy_defect_occupation,
    phi_min_3mtpa,
    phi_max_3mtpa,
    binding_vacancy_interaction,
    spb_coordination,
    hydrogen_bond_3mtpa,
    fa_vacancy_energy,
    nmr_hydrogen_bonding,
    xps_pb_shift,
    sims_signal_ratio,
    pl_intensity_mapping,
    morphology_unchanged,
    no_low_dim_perovskite,
    ta_single_bleach,
    trpl_control_lifetime,
    trpl_pda_limited,
    trpl_3mtpai_plateau,
    ups_cbm_fermi,
    ntype_doping_field_effect,
    plqy_improvement,
    no_interference,
    photovoltaic_params,
    dark_saturation_current,
    champion_device_jv,
    qss_pce_certification,
    large_area_device,
    thermal_stability,
    operating_stability,
    universality_wbg,
    universality_nbg,
    tandem_architecture,
    tandem_pce,
    strat_dmdp_combined_effect,
    strat_dmdp_enables_high_pce,
    strat_dmdp_enables_stability,
    obs_quasi_steady_state_pce,
    alt_control_single_molecule,
    pred_dmdp,
    pred_single,
    s_dmdp,
    s_alt,
    comp,
    abd_dmdp_vs_single,
)

from .s4_discussion import (
    dmdp_mitigation,
    carrier_lifetime_improvement,
    plqy_loss_reduction,
    certified_quasi_steady_state,
    stable_operation,
    tandem_achievement,
    future_direction,
    strat_dmdp_strategy,
    ind_tandem,
)

__all__ = [
    # Motivation
    "regular_pscs_pce",
    "inverted_psc_advantages",
    "inverted_psc_pce_gap",
    "interface_recombination",
    "near_interface_minority_carriers",
    "surface_defect_recombination",
    "surface_passivation_suppresses",
    "single_molecule_insufficient",
    "dual_passivation_concept",
    "diammonium_field_effect",
    "methylthio_chemical_passivation",
    # Methods
    "device_architecture",
    "control_device_pce",
    "dianmmonium_pce_improvement",
    "dianmmonium_field_effect_mechanism",
    "bai_chemical_passivation",
    "aai_improves_baseline",
    "methylthio_synthesis",
    "dual_combinations_improve",
    "pai2_3mtpai_highest_pce",
    "strat_dianmmonium_methylthio",
    # Results
    "binding_energy_3mtpa",
    "vacancy_defect_occupation",
    "phi_min_3mtpa",
    "phi_max_3mtpa",
    "binding_vacancy_interaction",
    "spb_coordination",
    "hydrogen_bond_3mtpa",
    "fa_vacancy_energy",
    "nmr_hydrogen_bonding",
    "xps_pb_shift",
    "sims_signal_ratio",
    "pl_intensity_mapping",
    "morphology_unchanged",
    "no_low_dim_perovskite",
    "ta_single_bleach",
    "trpl_control_lifetime",
    "trpl_pda_limited",
    "trpl_3mtpai_plateau",
    "ups_cbm_fermi",
    "ntype_doping_field_effect",
    "plqy_improvement",
    "no_interference",
    "photovoltaic_params",
    "dark_saturation_current",
    "champion_device_jv",
    "qss_pce_certification",
    "large_area_device",
    "thermal_stability",
    "operating_stability",
    "universality_wbg",
    "universality_nbg",
    "tandem_architecture",
    "tandem_pce",
    "strat_dmdp_combined_effect",
    "strat_dmdp_enables_high_pce",
    "strat_dmdp_enables_stability",
    "obs_quasi_steady_state_pce",
    "alt_control_single_molecule",
    "pred_dmdp",
    "pred_single",
    "s_dmdp",
    "s_alt",
    "comp",
    "abd_dmdp_vs_single",
    # Discussion
    "dmdp_mitigation",
    "carrier_lifetime_improvement",
    "plqy_loss_reduction",
    "certified_quasi_steady_state",
    "stable_operation",
    "tandem_achievement",
    "future_direction",
    "strat_dmdp_strategy",
    "ind_tandem",
]