"""
Jeon et al. 2014 (pvsk2014-gaia): Solvent engineering for high-performance
inorganic-organic hybrid perovskite solar cells.

Package exports the key claims, settings, and strategies from the paper.
"""

from .motivation import (
    perovskite_optical_properties,
    perovskite_ambipolar_transport,
    perovskite_long_diffusion_lengths,
    sequential_deposition_benchmark,
    vacuum_deposition_benchmark,
    spin_coating_problem,
    uniformity_limitation,
    research_question,
    bilayer_architecture,
    perovskite_composition,
    mixed_solvent_solution,
    certified_efficiency,
)

from .s2_methods import (
    device_architecture,
    blocking_layer_spec,
    mesoporous_layer_spec,
    perovskite_upper_layer_thickness,
    hole_transporting_layer,
    gold_counterelectrode,
    active_area,
    solvent_engineering_process,
    pure_gbl_outcome,
    mixed_solvent_outcome,
    without_toluene_outcome,
    crystallinity_preserved,
    intermediate_phase_formation,
    dmso_retards_reaction,
    intermediate_phase_identity,
    elemental_analysis_confirms,
    low_angle_xrd_peaks,
    ftir_confirmation,
    perovskite_conversion_temperature,
    intermediate_phase_rms_roughness,
    perovskite_film_rms_roughness,
    dense_grained_morphology,
    full_surface_coverage,
    xrd_method,
    ftir_method,
    uv_vis_method,
    afm_method,
    ipce_method,
    jv_measurement_method,
    elemental_analysis_method,
)

from .s3_results import (
    no_mp_tio2_forward_scan,
    no_mp_tio2_reverse_scan,
    large_hysteresis_without_mp,
    delay_time_effect,
    bilayer_forward_scan,
    bilayer_reverse_scan,
    negligible_hysteresis_bilayer,
    average_bilayer_efficiency,
    thickness_vs_efficiency,
    hysteresis_origin,
    best_cell_average,
    ipce_plateau,
    jsc_from_ipce,
    reproducibility_histogram,
    certified_efficiency_162,
    balanced_thickness_concept,
)

from .s4_discussion import (
    formation_mechanism,
    intermediate_phase_critical,
    role_of_dmso,
    role_of_toluene,
    solid_state_conversion,
    bilayer_advantages,
    mp_tio2_necessity,
    solvent_engineering_contribution,
    intercalation_strategy,
    key_achievement,
)

from .s5_strategies import (
    strat_intermediate_phase_uniformity,
    strat_xrd_identity,
    strat_crystallinity,
    strat_morphology,
    strat_bilayer_eliminates_hysteresis,
    strat_bilayer_efficiency,
    strat_mechanism_explains,
    strat_thickness_optimization,
    strat_reproducibility,
    strat_intercalation,
    strat_solution_approach,
    strat_benchmark_comparison,
    strat_ipce_validation,
)

__all__ = [
    # motivation
    "perovskite_optical_properties",
    "perovskite_ambipolar_transport",
    "perovskite_long_diffusion_lengths",
    "sequential_deposition_benchmark",
    "vacuum_deposition_benchmark",
    "spin_coating_problem",
    "uniformity_limitation",
    "research_question",
    "bilayer_architecture",
    "perovskite_composition",
    "mixed_solvent_solution",
    "certified_efficiency",
    # s2_methods
    "device_architecture",
    "blocking_layer_spec",
    "mesoporous_layer_spec",
    "perovskite_upper_layer_thickness",
    "hole_transporting_layer",
    "gold_counterelectrode",
    "active_area",
    "solvent_engineering_process",
    "pure_gbl_outcome",
    "mixed_solvent_outcome",
    "without_toluene_outcome",
    "crystallinity_preserved",
    "intermediate_phase_formation",
    "dmso_retards_reaction",
    "intermediate_phase_identity",
    "elemental_analysis_confirms",
    "low_angle_xrd_peaks",
    "ftir_confirmation",
    "perovskite_conversion_temperature",
    "intermediate_phase_rms_roughness",
    "perovskite_film_rms_roughness",
    "dense_grained_morphology",
    "full_surface_coverage",
    "xrd_method",
    "ftir_method",
    "uv_vis_method",
    "afm_method",
    "ipce_method",
    "jv_measurement_method",
    "elemental_analysis_method",
    # s3_results
    "no_mp_tio2_forward_scan",
    "no_mp_tio2_reverse_scan",
    "large_hysteresis_without_mp",
    "delay_time_effect",
    "bilayer_forward_scan",
    "bilayer_reverse_scan",
    "negligible_hysteresis_bilayer",
    "average_bilayer_efficiency",
    "thickness_vs_efficiency",
    "hysteresis_origin",
    "best_cell_average",
    "ipce_plateau",
    "jsc_from_ipce",
    "reproducibility_histogram",
    "certified_efficiency_162",
    "balanced_thickness_concept",
    # s4_discussion
    "formation_mechanism",
    "intermediate_phase_critical",
    "role_of_dmso",
    "role_of_toluene",
    "solid_state_conversion",
    "bilayer_advantages",
    "mp_tio2_necessity",
    "solvent_engineering_contribution",
    "intercalation_strategy",
    "key_achievement",
    # s5_strategies
    "strat_intermediate_phase_uniformity",
    "strat_xrd_identity",
    "strat_crystallinity",
    "strat_morphology",
    "strat_bilayer_eliminates_hysteresis",
    "strat_bilayer_efficiency",
    "strat_mechanism_explains",
    "strat_thickness_optimization",
    "strat_reproducibility",
    "strat_intercalation",
    "strat_solution_approach",
    "strat_benchmark_comparison",
    "strat_ipce_validation",
]