"""
PVSK 2015 (Jeon et al., Nature 2015) knowledge package.

Compositional engineering of perovskite materials for high-performance solar cells.
"""

from .motivation import (
    perovskite_structure,
    mapbi3_properties,
    fapbi3_properties,
    fapbi3_phase_instability,
    fapbi3_lower_performance,
    research_question,
    mixed_cation_pellet,
    prior_work_seok,
    mapbi3_transport,
    fapbi3_transport,
    conductivity_type,
)

from .s2_methods import (
    composition_system,
    device_architecture,
    solvent_engineering,
    annealing_conditions,
    mai_synthesis,
    fai_synthesis,
    mabr_synthesis,
    fabr_synthesis,
    perovskite_solution,
    tio2_nanoparticles,
    tio2_paste,
    blocking_layer,
    mesoporous_layer,
    ptaa_deposition,
    au_electrode,
    xrd_method,
    uvvis_method,
    sem_method,
    dsc_tga_method,
    eqe_method,
    jv_measurement,
)

from .s3_results import (
    table1_pce_trend,
    table1_photovoltaic_parameters,
    jsc_maximum,
    voc_increases_with_x,
    ff_maximum,
    series_resistance,
    fapbi3_hysteresis,
    absorption_blue_shift,
    eqe_blue_shift,
    eqe_plateau,
    dsc_phase_transition,
    phase_reversibility,
    perovskite_polymorphs,
    xrd_nonperovskite_x0,
    xrd_perovskite_x15,
    synergetic_effect,
    fwhm_crystallinity,
    black_powder_only,
    sem_morphology_x0,
    sem_morphology_x15,
    best_device_jv,
    certified_pce,
    hysteresis_80nm,
)

from .s4_discussion import (
    main_conclusion,
    synergy_mechanism,
    phase_stabilization_evidence,
    morphology_improvement,
    bandgap_tuning_tradeoff,
    hysteresis_benefit,
    comparison_mapbi3,
    comparison_fapbi3,
    comparison_prior_mixed,
    future_potential,
    understanding_phase_stability,
    need_further_study,
    strat_main_conclusion,
    strat_phase_evidence,
    strat_morphology_evidence,
    strat_pce_trend,
    strat_synergy,
    strat_hysteresis,
    strat_jv_consistency,
    strat_polymorph_evidence,
    strat_compare_mapbi3,
    strat_compare_fapbi3,
)

__all__ = [
    # motivation
    "perovskite_structure",
    "mapbi3_properties",
    "fapbi3_properties",
    "fapbi3_phase_instability",
    "fapbi3_lower_performance",
    "research_question",
    "mixed_cation_pellet",
    "prior_work_seok",
    "mapbi3_transport",
    "fapbi3_transport",
    "conductivity_type",
    # s2_methods
    "composition_system",
    "device_architecture",
    "solvent_engineering",
    "annealing_conditions",
    "mai_synthesis",
    "fai_synthesis",
    "mabr_synthesis",
    "fabr_synthesis",
    "perovskite_solution",
    "tio2_nanoparticles",
    "tio2_paste",
    "blocking_layer",
    "mesoporous_layer",
    "ptaa_deposition",
    "au_electrode",
    "xrd_method",
    "uvvis_method",
    "sem_method",
    "dsc_tga_method",
    "eqe_method",
    "jv_measurement",
    # s3_results
    "table1_pce_trend",
    "table1_photovoltaic_parameters",
    "jsc_maximum",
    "voc_increases_with_x",
    "ff_maximum",
    "series_resistance",
    "fapbi3_hysteresis",
    "absorption_blue_shift",
    "eqe_blue_shift",
    "eqe_plateau",
    "dsc_phase_transition",
    "phase_reversibility",
    "perovskite_polymorphs",
    "xrd_nonperovskite_x0",
    "xrd_perovskite_x15",
    "synergetic_effect",
    "fwhm_crystallinity",
    "black_powder_only",
    "sem_morphology_x0",
    "sem_morphology_x15",
    "best_device_jv",
    "certified_pce",
    "hysteresis_80nm",
    # s4_discussion
    "main_conclusion",
    "synergy_mechanism",
    "phase_stabilization_evidence",
    "morphology_improvement",
    "bandgap_tuning_tradeoff",
    "hysteresis_benefit",
    "comparison_mapbi3",
    "comparison_fapbi3",
    "comparison_prior_mixed",
    "future_potential",
    "understanding_phase_stability",
    "need_further_study",
]