from .motivation import (
    solid_state_sensitized_solar_cells_background,
    perovskite_nanocrystals_as_light_harvesters,
    pce_9_7_percent,
    jsc_17_6_ma_cm2,
    voc_0_888_v,
    ff_0_62,
    ipce_over_50_percent,
    bandgap_1_5_ev,
    tiO2_bandgap_3_1_ev,
    evb_minus_5_43_ev,
    ecb_minus_3_93_ev,
    stability_improvement,
    charge_separation_mechanism,
    device_structure,
    absorption_coefficient,
)

from .s2_methods import (
    kubelka_munk_method,
    ups_measurement,
    pia_spectroscopy,
    femtosecond_tas,
    impedance_spectroscopy,
    perovskite_synthesis,
    tiO2_nanoparticle_synthesis,
    device_fabrication,
)

from .s3_results import (
    jsc_vs_tio2_thickness,
    voc_vs_tio2_thickness,
    ff_vs_tio2_thickness,
    pce_vs_tio2_thickness,
    dark_current_scaled_linearly,
    recombination_resistance_decreased,
    electron_lifetime_decreased,
    band_edge_emission_780nm,
    exciton_decay_multiexponential,
    reductive_quenching_observed,
    hole_injection_mechanism,
    delta_voc_reduction,
)

from .s4_discussion import (
    panchromatic_absorption_leads_to_high_jsc,
    charge_separation_well_aligned,
    solid_state_dramatically_improved_stability,
    pce_9_7_percent_conclusion,
    strat_panchromatic_absorption,
    strat_charge_separation,
    strat_stability,
    strat_pce_conclusion,
    strat_bandgap_evidence,
    stability_observation_1,
    stability_observation_2,
    stability_observation_3,
    strat_stability_obs,
    pce_prediction_from_individual_params,
)

__all__ = [
    # Core exported conclusions
    "pce_9_7_percent",
    "jsc_17_6_ma_cm2",
    "voc_0_888_v",
    "ff_0_62",
    "ipce_over_50_percent",
    "bandgap_1_5_ev",
    "tiO2_bandgap_3_1_ev",
    "evb_minus_5_43_ev",
    "ecb_minus_3_93_ev",
    "stability_improvement",
    "charge_separation_mechanism",
    "device_structure",
    "absorption_coefficient",
    # Methods
    "kubelka_munk_method",
    "ups_measurement",
    "pia_spectroscopy",
    "femtosecond_tas",
    "impedance_spectroscopy",
    "perovskite_synthesis",
    "tiO2_nanoparticle_synthesis",
    "device_fabrication",
    # Results
    "jsc_vs_tio2_thickness",
    "voc_vs_tio2_thickness",
    "ff_vs_tio2_thickness",
    "pce_vs_tio2_thickness",
    "dark_current_scaled_linearly",
    "recombination_resistance_decreased",
    "electron_lifetime_decreased",
    "band_edge_emission_780nm",
    "exciton_decay_multiexponential",
    "reductive_quenching_observed",
    "hole_injection_mechanism",
    "delta_voc_reduction",
    # Discussion
    "panchromatic_absorption_leads_to_high_jsc",
    "charge_separation_well_aligned",
    "solid_state_dramatically_improved_stability",
    "pce_9_7_percent_conclusion",
    # Strategies (for BP)
    "strat_panchromatic_absorption",
    "strat_charge_separation",
    "strat_stability",
    "strat_pce_conclusion",
    "strat_bandgap_evidence",
    "stability_observation_1",
    "stability_observation_2",
    "stability_observation_3",
    "strat_stability_obs",
    "pce_prediction_from_individual_params",
]