from gaia.lang import (
    claim,
    setting,
    support,
    deduction,
)

__all__ = [
    "kubelka_munk_method",
    "ups_measurement",
    "pia_spectroscopy",
    "femtosecond_tas",
    "impedance_spectroscopy",
    "perovskite_synthesis",
    "tiO2_nanoparticle_synthesis",
    "device_fabrication",
]


# ===== METHODS =====

kubelka_munk_method = setting(
    "The optical absorption coefficient (alpha) is calculated from reflectance data using the Kubelka-Munk equation: F(R) = alpha = (1-R)^2 / 2R, where R is the percentage of reflected light. The band gap energy (Eg) is related to the transformed Kubelka-Munk function: [F(R)hv]^p = A(hv - Eg), where p = 1/2 or 2 for indirect or direct allowed transitions respectively."
)

ups_measurement = setting(
    "Ultraviolet photoelectron spectroscopy (UPS) measures the valence band energy (EVB) of a material. The energy is calibrated with respect to He I photon energy (21.21 eV)."
)

# Materials synthesis method description
perovskite_synthesis = claim(
    "The CH3NH3PbI3 perovskite sensitizer was prepared by reaction of methylammonium iodide (CH3NH3I) with PbI2. CH3NH3I was synthesized by stirring hydroiodic acid with methylamine in an ice bath for 2 hours, then evaporating at 50 degrees C for 1 hour. The product was washed three times with diethyl ether and dried under vacuum. CH3NH3I was then mixed with PbI2 in gamma-butyrolactone at 60 degrees C overnight with stirring.",
    title="Perovskite synthesis method"
)

tiO2_nanoparticle_synthesis = claim(
    "Anatase TiO2 nanoparticles were synthesized by acetic acid catalyzed hydrolysis of titanium isopropoxide, followed by autoclaving at 230 degrees C for 12 hours. The aqueous solvent was replaced by ethanol to prepare non-aqueous TiO2 paste. The nominal composition of TiO2/terpineol/ethylcellulose/lauric acid was 1/6/0.3/0.1 by weight.",
    title="TiO2 nanoparticle synthesis"
)

device_fabrication = claim(
    "FTO glasses were cleaned ultrasonically in ethanol for 15 min and treated with UVO for 15 min. A dense TiO2 blocking layer was formed by spin-coating with titanium diisopropoxide bis(acetylacetonate) solution, heated at 125 degrees C for 5 min, repeated twice at increasing concentrations, then heated at 500 degrees C for 15 min. Mesoporous TiO2 paste was deposited by doctor-blade and annealed at 550 degrees C for 1 hour. After TiCl4 treatment at 70 degrees C for 10 min and heating at 500 degrees C for 30 min, the films were coated with perovskite precursor solution and heated at 100 degrees C for 15 min. The HTM solution (spiro-MeOTAD with LiTFSI and TBP in chlorobenzene:acetonitrile) was spin-coated at 4000 rpm. A 60 nm Au counter electrode was deposited by thermal evaporation.",
    title="Device fabrication protocol"
)

# Characterization methods
pia_spectroscopy = setting(
    "Photo-induced absorption (PIA) spectroscopy probes photo-generated charge species using a white light probe beam and modulated pump light source. A 20 W halogen lamp serves as the probe source, with a dual color solid-state detector (Si/InGaAs) achieving an effective spectral range of 300-1650 nm."
)

femtosecond_tas = setting(
    "Femtosecond transient absorption spectra were recorded using a pump-probe setup. The pump beam (lambda_exc = 580 nm) was generated by a two-stage non-collinear optical parametric amplifier (NOPA) pumped by a 778 nm amplified Ti:Sa laser system (150 fs duration pulses at 1 kHz repetition rate). The probe consisted of a white light continuum (430-1000 nm) generated by passing 778 nm light through a 3 mm sapphire plate."
)

impedance_spectroscopy = setting(
    "Electrochemical impedance measurements were performed with a Bio-Logic SP-300 potentiostat. A sinusoidal AC potential perturbation of 15 mV was overlaid over the applied DC bias potential, with frequency range from 1 MHz to 0.1 Hz. The measurements were fitted with a simple RC element (R and C in parallel) in series with a resistance."
)
