[project]
name = "pvsk-gaia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vv910", email = "huangwzh33@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gaia-lang>=0.4.4",
]

[build-system]
requires = ["uv_build>=0.8.10,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "pvsk"

[tool.gaia]
type = "knowledge-package"
uuid = "367c509b-1e03-4b04-9e62-0007fc4930e7"
